- targets:  # url;humanname;routing;switch
    - http://www.google.com/;google.com;external;internetbox
    - https://github.com/;github.com;external;internetbox
    - https://www.tdgunes.com;tdgunes.com;external;internetbox


